# Generated by Django 4.2.3 on 2023-07-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type_creatures', models.CharField(choices=[('P', 'Passive'), ('N', 'Neutral'), ('H', 'Hostile'), ('B', 'Bosses'), ('Nu', 'Not used'), ('E', 'Eliminated'), ('J', 'Joke'), ('Ni', 'Not implemented')], max_length=2)),
                ('health_points', models.PositiveIntegerField()),
                ('biome', models.CharField(max_length=50)),
                ('drop', models.CharField(max_length=150)),
                ('special_action', models.TextField()),
            ],
        ),
    ]
