# Generated by Django 4.2.3 on 2023-07-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatures',
            name='type_creatures',
            field=models.CharField(choices=[('Bosses', 'Bosses'), ('Hostile', 'Hostile'), ('Joke', 'Joke'), ('Neutral', 'Neutral'), ('Passive', 'Passive'), ('Eliminated', 'Eliminated'), ('Not implemented', 'Not implemented'), ('Not used', 'Not used')], max_length=20),
        ),
    ]
