# Generated by Django 4.2.3 on 2023-07-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_creatures_type_creatures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Creatures',
            new_name='Creature',
        ),
        migrations.RenameField(
            model_name='creature',
            old_name='type_creatures',
            new_name='type_creature',
        ),
    ]
