# Generated by Django 4.2.3 on 2023-07-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_creatures_creature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
